In [16]:
import pandas as pd
df=pd.read_csv('/home/pavank/Desktop/cutoff - price.csv')
df = df[df['id'].notna()]
for index, row in df.iterrows():
    print(int(row['id']),int(row['cutoff_price']))

(2, 300000)
(5, 750000)
(6, 400000)
(7, 550000)
(49, 250000)
(61, 600000)
(64, 500000)
(70, 350000)
(76, 450000)
(91, 1350000)
(115, 650000)
(121, 300000)
(123, 300000)
(126, 500000)
(132, 800000)
(145, 1100000)
(148, 250000)
(150, 600000)
(152, 850000)
(156, 300000)
(159, 400000)
(160, 400000)
(167, 750000)
(174, 300000)
(177, 250000)
(179, 300000)
(182, 600000)
(183, 300000)
(184, 250000)
(196, 400000)
(199, 550000)
(202, 250000)
(205, 700000)
(209, 350000)
(210, 250000)
(212, 300000)
(217, 300000)
(228, 450000)
(229, 350000)
(240, 950000)
(241, 500000)
(242, 250000)
(248, 200000)
(249, 600000)
(253, 750000)
(260, 200000)
(264, 450000)
(265, 450000)
(285, 450000)
(292, 750000)
(299, 150000)
(301, 150000)
(303, 500000)
(304, 350000)
(306, 250000)
(310, 350000)
(314, 150000)
(317, 550000)
(330, 250000)
(354, 700000)
(355, 550000)
(363, 400000)
(365, 400000)
(374, 400000)
(376, 450000)
(379, 1000000)
(380, 400000)
(381, 600000)
(386, 600000)
(438, 250000)
(440, 700000)
(449, 250000)
(463, 150000)
(464, 100000)
(465, 150000)
(468, 300000)
(469, 200000)
(471, 200000)
(477, 150000)
(478, 150000)
(479, 450000)
(480, 350000)
(481, 100000)
(482, 450000)
(483, 150000)
(484, 500000)
(494, 100000)
(497, 150000)
(510, 250000)
(511, 700000)
(512, 350000)
(513, 300000)
(515, 450000)
(516, 1100000)
(517, 750000)
(521, 400000)
(523, 800000)
(527, 750000)
(533, 950000)
(537, 400000)
(543, 850000)
(544, 450000)
(545, 500000)
(546, 300000)
(552, 500000)
(558, 1500000)
(564, 350000)
(567, 300000)
(580, 600000)
(590, 250000)
(596, 350000)
(598, 300000)
(600, 500000)
(609, 150000)
(630, 2100000)
(641, 300000)
(660, 450000)
(662, 650000)

In [ ]:

INSERT INTO  models(id, cutoff_price) VALUES (2, 300000), (5, 750000), (6, 400000), (7, 550000), (49, 250000),
                                            (61, 600000), (64, 500000), (70, 350000), (76, 450000), (91, 1350000),
                                            (115, 650000), (121, 300000), (123, 300000), (126, 500000), (132, 800000),
                                            (145, 1100000), (148, 250000), (150, 600000), (152, 850000), (156, 300000),
                                            (159, 400000), (160, 400000), (167, 750000), (174, 300000), (177, 250000),
                                            (179, 300000), (182, 600000), (183, 300000), (184, 250000), (196, 400000),
                                            (199, 550000), (202, 250000), (205, 700000), (209, 350000), (210, 250000),
                                            (212, 300000), (217, 300000), (228, 450000), (229, 350000), (240, 950000),
                                            (241, 500000), (242, 250000), (248, 200000), (249, 600000), (253, 750000),
                                            (260, 200000), (264, 450000), (265, 450000), (285, 450000), (292, 750000),
                                            (299, 150000), (301, 150000), (303, 500000), (304, 350000), (306, 250000),
                                            (310, 350000), (314, 150000), (317, 550000), (330, 250000), (354, 700000),
                                            (355, 550000), (363, 400000), (365, 400000), (374, 400000), (376, 450000),
                                            (379, 1000000), (380, 400000), (381, 600000), (386, 600000), (438, 250000),
                                            (440, 700000), (449, 250000), (463, 150000), (464, 100000), (465, 150000),
                                            (468, 300000), (469, 200000), (471, 200000), (477, 150000), (478, 150000),
                                            (479, 450000), (480, 350000), (481, 100000), (482, 450000), (483, 150000),
                                            (484, 500000), (494, 100000), (497, 150000), (510, 250000), (511, 700000),
                                            (512, 350000), (513, 300000), (515, 450000), (516, 1100000), (517, 750000),
                                            (521, 400000), (523, 800000), (527, 750000), (533, 950000), (537, 400000),
                                            (543, 850000), (544, 450000), (545, 500000), (546, 300000), (552, 500000),
                                            (558, 1500000), (564, 350000), (567, 300000), (580, 600000), (590, 250000),
                                            (596, 350000), (598, 300000), (600, 500000), (609, 150000), (630, 2100000),
                                            (641, 300000), (660, 450000), (662, 650000)
ON DUPLICATE KEY UPDATE cutoff_price = VALUES(cutoff_price);


â€‹